name: Lib Deploy

on:
    push:
        tags:
            - "*"
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: 16

            - run: npm i -g pnpm
            - run: pnpm install

            - name: Build
              run: pnpm build:lib && pnpm build:docs

            - name: Deploy Lib
              run: cd packages/admin-component && npm publish
              env:
                  NPM_TOKEN: ${{ secrets.EASYFE_NPM_TOKEN }}

            - name: Deploy Docs
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: packages/docs/.vitepress/dist

            - name: Get version
              id: get_version
              run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

            - name: Create Release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.get_version.outputs.VERSION }}
                  release_name: ${{ steps.get_version.outputs.VERSION }}
                  draft: false
                  prerelease: false
